services:
  origin:
    image: nginx:latest
    container_name: origin
    volumes:
      - ./audio:/usr/share/nginx/html/audio:ro
      - ./player.html:/usr/share/nginx/html/player.html:ro
      - ./origin.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  edge1:
    image: nginx:latest
    container_name: edge1
    volumes:
      - "./edge.conf:/etc/nginx/conf.d/default.conf:ro"
      - edge1_cache:/var/cache/nginx
    ports:
      - "8081:80"

  edge2:
    image: nginx:latest
    container_name: edge2
    volumes:
      - "./edge.conf:/etc/nginx/conf.d/default.conf:ro"
      - edge2_cache:/var/cache/nginx
    ports:
      - "8082:80"

  edge3:
    image: nginx:latest
    container_name: edge3
    volumes:
      - "./edge.conf:/etc/nginx/conf.d/default.conf:ro"
      - edge3_cache:/var/cache/nginx
    ports:
      - "8083:80"

volumes:
  edge1_cache:
  edge2_cache:
  edge3_cache:
