name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push origin image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.origin
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cdn-origin:latest

      - name: Build and push edge image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.edge
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cdn-edge:latest
